version: "2"
services:
  krakatoa-api:
    build: .
    environment:
      - MONGO_URI=mongodb://mongodb:27017/krakatoa
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    tty: true

  mongodb:
    image: mongo
    ports:
      - "27017:27017"